name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}

    runs-on: ubuntu-latest

    strategy:
      matrix: { ruby: ['2.4', '2.5', '2.6', '2.7', '3.0'] }

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with: 
        ruby-version: '${{ matrix.ruby }}'
        bundler-cache: true

    - name: Start mock server
      run: |
        bundle exec run mockserver --daemon
        sleep 2

    - name: Run tests
      run: bundle exec rspec
